name: Verify & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Minimal, always-safe verification demo:
      # Hash README.md, append a JSON line, and copy the log into docs/
      - name: Verify and update log
        run: |
          set -e
          ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          sha=$(sha256sum README.md | awk '{print $1}')
          echo "{\"timestamp\":\"$ts\",\"file\":\"README.md\",\"sha256\":\"$sha\",\"status\":\"ok\",\"commit\":\"${GITHUB_SHA}\"}" >> repro_log.jsonl
          mkdir -p docs
          cp repro_log.jsonl docs/repro_log.jsonl

      - name: Commit updated repro log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add repro_log.jsonl docs/repro_log.jsonl
          if ! git diff --cached --quiet; then
            git commit -m "chore: append repro log [skip ci]"
            git push
          fi

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload dashboard
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
